-- =====================================================================
-- NOTIFICAÇÕES DO ANIMESPOT
-- =====================================================================
-- Como usar:
--   1. Abra o painel do Supabase > SQL Editor > New query
--   2. Cole TODO este arquivo e clique em "Run"
--
-- O que este script faz:
--   - Cria a tabela "notificacoes"
--   - Cria gatilhos (triggers) que geram notificações automaticamente:
--       * alguém começou a seguir você           (tabela seguidores)
--       * saiu capítulo novo de uma obra favorita (tabela capitulos)
--       * alguém comentou na sua postagem         (tabela comentarios)
--       * alguém curtiu sua postagem              (tabela curtidas)
--
-- Pode rodar mais de uma vez sem problema.
-- =====================================================================


-- ---------------------------------------------------------------------
-- TABELA
-- ---------------------------------------------------------------------

create table if not exists public.notificacoes (
    id          bigint generated by default as identity primary key,
    id_usuario  bigint not null references public.usuarios(id) on delete cascade,
    tipo        text not null,              -- 'seguidor' | 'capitulo' | 'comentario' | 'curtida'
    mensagem    text not null,
    link        text,                       -- página que abre ao clicar
    lida        boolean not null default false,
    criado_em   timestamptz not null default now()
);

create index if not exists notificacoes_id_usuario_idx
    on public.notificacoes (id_usuario, lida);

-- As outras tabelas do projeto estão com RLS desligado,
-- então esta também fica igual por enquanto.
alter table public.notificacoes disable row level security;

-- Garantia: se o Supabase religar o RLS sozinho, esta regra libera tudo
drop policy if exists "notificacoes_liberado" on public.notificacoes;
create policy "notificacoes_liberado"
    on public.notificacoes
    for all
    to anon, authenticated
    using (true)
    with check (true);


-- ---------------------------------------------------------------------
-- NOVO SEGUIDOR
-- ---------------------------------------------------------------------

create or replace function public.notificar_novo_seguidor()
returns trigger
language plpgsql
security definer          -- roda com permissão do dono: o RLS não bloqueia o gatilho
set search_path = public
as $$
declare
    nome_seguidor text;
begin
    select username into nome_seguidor
    from public.usuarios
    where id = new.id_seguidor;

    insert into public.notificacoes (id_usuario, tipo, mensagem, link)
    values (
        new.id_seguido,
        'seguidor',
        '@' || coalesce(nome_seguidor, 'alguém') || ' começou a seguir você',
        '/Perfil/' || new.id_seguidor
    );

    return new;
end;
$$;

drop trigger if exists trg_notificar_novo_seguidor on public.seguidores;
create trigger trg_notificar_novo_seguidor
    after insert on public.seguidores
    for each row execute function public.notificar_novo_seguidor();


-- ---------------------------------------------------------------------
-- NOVO CAPÍTULO EM OBRA FAVORITADA
-- ---------------------------------------------------------------------

create or replace function public.notificar_novo_capitulo()
returns trigger
language plpgsql
security definer          -- roda com permissão do dono: o RLS não bloqueia o gatilho
set search_path = public
as $$
declare
    titulo_obra text;
    autor       bigint;
begin
    select titulo, autor_id into titulo_obra, autor
    from public.obras
    where id = new.id_obra;

    -- Uma notificação para cada pessoa que favoritou a obra
    -- (menos o próprio autor)
    insert into public.notificacoes (id_usuario, tipo, mensagem, link)
    select
        f.usuario_id,
        'capitulo',
        'Novo capítulo ' || new.numero_capitulo || ' de "' || titulo_obra || '"',
        '/Leitura/' || titulo_obra
    from public.favoritos f
    where f.obra_id = new.id_obra
      and f.usuario_id is distinct from autor;

    return new;
end;
$$;

drop trigger if exists trg_notificar_novo_capitulo on public.capitulos;
create trigger trg_notificar_novo_capitulo
    after insert on public.capitulos
    for each row execute function public.notificar_novo_capitulo();


-- ---------------------------------------------------------------------
-- NOVO COMENTÁRIO NA SUA POSTAGEM
-- ---------------------------------------------------------------------

create or replace function public.notificar_novo_comentario()
returns trigger
language plpgsql
security definer          -- roda com permissão do dono: o RLS não bloqueia o gatilho
set search_path = public
as $$
declare
    dono_postagem   bigint;
    titulo_postagem text;
    nome_autor      text;
begin
    select id_usuario, titulo into dono_postagem, titulo_postagem
    from public.postagens
    where id = new.id_postagem;

    -- Não avisa a pessoa sobre o próprio comentário
    if dono_postagem is null or dono_postagem = new.id_usuario then
        return new;
    end if;

    select username into nome_autor
    from public.usuarios
    where id = new.id_usuario;

    insert into public.notificacoes (id_usuario, tipo, mensagem, link)
    values (
        dono_postagem,
        'comentario',
        '@' || coalesce(nome_autor, 'alguém') || ' comentou na sua postagem "' || coalesce(titulo_postagem, '') || '"',
        '/'
    );

    return new;
end;
$$;

drop trigger if exists trg_notificar_novo_comentario on public.comentarios;
create trigger trg_notificar_novo_comentario
    after insert on public.comentarios
    for each row execute function public.notificar_novo_comentario();


-- ---------------------------------------------------------------------
-- NOVA CURTIDA NA SUA POSTAGEM
-- ---------------------------------------------------------------------

create or replace function public.notificar_nova_curtida()
returns trigger
language plpgsql
security definer          -- roda com permissão do dono: o RLS não bloqueia o gatilho
set search_path = public
as $$
declare
    dono_postagem   bigint;
    titulo_postagem text;
    nome_autor      text;
begin
    select id_usuario, titulo into dono_postagem, titulo_postagem
    from public.postagens
    where id = new.id_postagem;

    if dono_postagem is null or dono_postagem = new.id_usuario then
        return new;
    end if;

    select username into nome_autor
    from public.usuarios
    where id = new.id_usuario;

    insert into public.notificacoes (id_usuario, tipo, mensagem, link)
    values (
        dono_postagem,
        'curtida',
        '@' || coalesce(nome_autor, 'alguém') || ' curtiu sua postagem "' || coalesce(titulo_postagem, '') || '"',
        '/'
    );

    return new;
end;
$$;

drop trigger if exists trg_notificar_nova_curtida on public.curtidas;
create trigger trg_notificar_nova_curtida
    after insert on public.curtidas
    for each row execute function public.notificar_nova_curtida();
